{% set version = "1.4.6" %}
{% set sha256 = "3e6c5849bdcc757bbad4c02b661a96bc0dfabaaf022ef448c423ac88615e6c58" %}


package:
  name: anypytools
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/AnyBody-Research-Group/AnyPyTools/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  # Added to allow the pytest entry points in setup.py to work
  # This is also the reason for setuptools being a runtime dependency. 
  preserve_egg_dir: true
  skip: true  # [py2k or not win]

requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - h5py >=2.5
    - setuptools
    - pydoe
    - tqdm
    - scipy >=0.15
    - pygments_anyscript

test:
  imports:
    - anypytools

app:
  entry: AnyPyToolsTutorial.bat
  summary: Python tools and utilities for working with the AnyBody Modeling System
  icon: apt_icon.png
  type: web

about:
  home: https://github.com/AnyBody-Research-Group/AnyPyTools
  license: MIT
  license_file: LICENSE.txt
  summary: Python tools and utilities for working with the AnyBody Modeling System
  description: AnyPyTools is a toolkit for working with the AnyBody Modeling System (AMS) from Python. Its main purpose is to launch AnyBody simulations and collect results. It has a scheduler to launch multiple instances of AMS utilising computers with multiple cores. AnyPyTools makes it possible to run parameter and Monte
    Carlo studies more efficiently than from within the AnyBody Modeling System.
  dev_url: https://github.com/AnyBody-Research-Group/AnyPyTools
  doc_url: https://anybody-research-group.github.io/anypytools-docs

extra:
  recipe-maintainers:
    - melund
