context:
  version: "1.18.0"
  sha256: 7dc13d938a55cc897ea457286ac84746e45fbba2548940d0d535d3f4267bc67e

package:
  name: anypytools
  version: ${{ version }}

source:
  url: https://github.com/AnyBody-Research-Group/AnyPyTools/archive/${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  skip:
    - osx
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - flit-core
    - pip
    - python
  run:
    - python
    - h5py >=2.5
    - setuptools
    - pydoe
    - rich
    - scipy >=0.15
    - pygments_anyscript
    - if: win
      then: pywin32


tests:
  - python:
      imports:
        - anypytools

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Python tools and utilities for working with the AnyBody Modeling System
  description: |
    AnyPyTools is a toolkit for working with the AnyBody Modeling System (AMS)
    from Python. Its main purpose is to launch AnyBody simulations and collect
    results. It has a scheduler to launch multiple instances of AMS utilising
    computers with multiple cores. AnyPyTools makes it possible to run
    parameter and Monte Carlo studies more efficiently than from within the
    AnyBody Modeling System.
  homepage: https://github.com/AnyBody-Research-Group/AnyPyTools
  repository: https://github.com/AnyBody-Research-Group/AnyPyTools
  documentation: https://anybody-research-group.github.io/anypytools-docs

extra:
  recipe-maintainers:
    - melund
