appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 6c9c0vyQ51m9HL/kbp3Tjkef38BzwmfMYutPnMSks2HC+/4NFbw3misy4/s790T3ih6ib4EUqF3iiysX2pCxNegxvDxhKbYIsOAvHfAcWjEcZ6UY5XMBhOagISad0fnyFs9+qPXgsC70zoblW3sDq5Df9PajEGF3gTNPiE99QTVN+JZPxmWuwPpHu4CdyczVOb51qtOsqRpKjsW/GzplZ5nsCmjmNJNoXqYuqBKSUvb4EVdnGoPT8Qm3EQmtaLwoHW3b91gIypTrU59J/HRwn7FTHe8B0rHkynw38AGfpdsRsHIXRwi+msF2jDHVTXaS7XKXpREjLQoelxWyjaCXfuIU/roId/mNW0Fu2eyvlHeKVFshiLkJ+zUUHxod16Vib+Xiy8Rkd5fhxAapAn/D182fYVwE3Mrxce2AGuHZV7oYR2GA4NGI0H/BSDPJhJT+R6p6JRHkVoxFvXghZ30ftH+BO/pq/4UdX4k7kiiTGDgjTv5ue6MXF8JFX9+RKYP+AMAhK4E1y9wOF/KpwKxKcIo6Twckt9zDKLsHyJL4fxR4H9aqpXpNzIOL3Rxtg4/+GiH/TH7Qp9ULIU3cK2rIfRTh5lalyG9biAfdWsxfGT/lPwX62t+S+vyfvRSKdcpexFqJAhrQHhuXa10evmgl83+lLR72yXipX4fBAFgLkfM=}
